server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      locator:
        enabled:true
    gateway:
      enabled: true
      routes:
        - id: auth-microservice
          uri: lb://auth-microservice
          predicates:
            - Path=/api/auth/**


        - id: user-microservice
          uri: lb://user-microservice
          predicates:
            - Path=/users/**

        - id: sales-microservice
          uri: lb://sales-microservice
          predicates:
            - Path=/sales/**

        - id: product-microservice
          uri: lb://product-microservice
          predicates:
            - Path=/product/**

        - id: delivery-microservice
          uri: lb://delivery-microservice
          predicates:
            - Path=/delivery/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true